### ISSUE TITLE
CypressQaseReporter : Result of last test of each spec is reported with start of next spec

### ISSUE THREAD

**Issue by martin-pikalek** [qase-tms/qase-javascript#120]
![Screenshot 2022-01-17 at 2 52 24](https://user-images.githubusercontent.com/57229273/149689095-129072a6-f6b4-4485-a7b5-676369b47c67.png)

When I start Cypress testing (with multiple spec files) result of last test of each spec is reported to Qase with start of next spec (due to Error in printscreen). Tests are not large, other results are reported quickly (max 1-2s). 

Issue: Last test of last spec is not reported (can be easily reproduced by running only 1 spec) - Cypress will terminate process before reporter could send last result (as next spec is not existing to not terminate process)

Actual workaround for me: Add sleep timer in cypress plugin file to process all background tasks.

- cypress/plugins/index.js

`
module.exports = async (on, config) => {
  on('after:run', async () => {
      await new Promise(resolve => setTimeout(resolve, 60000));
  })
}
`

**Comment by martin-pikalek** [comment]
@1ivliev can someone please look on it? This issue is still persisting and with high number of spec files, total runtime of tests is increased significantly as each spec file waits for 30s at the end for nothing (resulting always in error) and last testcase of each spec file is reported with the start of next spec file (which can result in not reported last testcase of last spec file - when not using mentioned workaround).

**Comment by 1ivliev** [comment]
@martin-pikalek hi! We are already working on solving this problem. I'll let you know when our PR is ready

**Comment by martin-pikalek** [comment]
@1ivliev thank you very much for response and information :)

**Comment by 1ivliev** [comment]
@martin-pikalek Good day! We have released an edit, please check if the situation you described repeats.

**Comment by martin-pikalek** [comment]
@1ivliev I will look on it 👍

**Comment by martin-pikalek** [comment]
@1ivliev it is under same npm version? I see latest version as 2.0.0-alpha.5 which I already had previously.

**Comment by 1ivliev** [comment]
@martin-pikalek, we are currently upgrading `cypress-qase-reporter`. I will inform you about the release of a new version.

**Comment by 1ivliev** [comment]
The interim version has been withdrawn and has not been assigned a tag.

**Comment by 1ivliev** [comment]
@martin-pikalek Hi!
We have updated the Cypress version to `qase-cypress-v1.4.2-alpha.2`
Please read the updated instructions before use.
If the problem persists, please let us know.

**Comment by martin-pikalek** [comment]
@1ivliev Hello,
I tried new version qase-cypress-v1.4.2-alpha.2 but I have major issues with it. I setup new repository with config (after reading new updated instructions), started new aut. tests, but only new Test Run is created within QASE, not single Test Result is sent to Qase.

**Comment by 1ivliev** [comment]
@martin-pikalek Hi!
Please make sure that you have set the permissions correctly in the project settings:
`Allow submitting results in bulk`
and
`Allow to add results for cases in closed runs.`
What error is returned to you in the console?

**Comment by martin-pikalek** [comment]
These permissions are set up on that project in QASE. Sending you terminal log from that run and also screenshot of cypress config json.
[terminal-log.txt](https://github.com/qase-tms/qase-javascript/files/8618526/terminal-log.txt)
![cypress-config](https://user-images.githubusercontent.com/57229273/166638538-7e5d9119-e0e6-4ea5-8eb3-b36ac40f57e2.png)
![Screenshot 2022-05-04 at 9 25 45](https://user-images.githubusercontent.com/57229273/166638557-be17ba39-cf72-434e-b437-c1688ea13ec9.png)

**Comment by martin-pikalek** [comment]
I did not see any specific error in terminal which would lead to not sending results.

**Comment by 1ivliev** [comment]
Please make sure that you send the correct `environmentId` (if you require it) as well as a valid `apiToken`
Try using the test build:
https://github.com/1ivliev/cypress-test

**Comment by martin-pikalek** [comment]
@1ivliev apiToken was removed only for screenshot of cypress config but apiToken and environmentId is correctly set as Test Run is correctly created in QASE (as can be seen in print screen from QASE). TestRun is created (so connection to Qase and specific Project is established) but no results are visible in QASE for that TestRun.

I will try it with the test build you created.
