### ISSUE TITLE
CypressQaseReporter: Test result is not published to Qase due to some unknown error

### ISSUE THREAD

**Issue by martin-pikalek** [qase-tms/qase-javascript#121]
![Screenshot 2022-01-17 at 3 14 55](https://user-images.githubusercontent.com/57229273/149690962-ef817299-bda7-437a-9653-990d93cf2851.png)

Issue: As can printscreen is showing, there is Error: getaddrinfo and case 18 result was not published (not sent to Qase)

Other reports were reported back to Qase and I did not recognise some network issues.

**Comment by 1ivliev** [comment]
@martin-pikalek hi! Can you send us test #18 or an example very similar to it?

**Comment by 1ivliev** [comment]
@martin-pikalek hi! Can you send us test №18 or an example very similar to it?

**Comment by 1ivliev** [comment]
@martin-pikalek, hi! Can you send us test №18 or an example very similar to it?

**Comment by martin-pikalek** [comment]
@1ivliev hello, this error was showed to me only 1 time. From that time I did not saw this error. I couldn't reproduce this error anymore. I think we can close this issue until it will show again.

**Comment by 1ivliev** [comment]
Let's do that. You can close the issue and reopen it if the problem happens again.
