### ISSUE TITLE
CypressQaseReporter: Skipped tests are not reported to Qase

### ISSUE THREAD

**Issue by martin-pikalek** [qase-tms/qase-javascript#122]
![Screenshot 2022-01-17 at 3 36 31](https://user-images.githubusercontent.com/57229273/149699769-ca5efaf8-c65b-4193-857c-61b633f88497.png)

Cypress have 4 test states:

1. passed
2. failed
3. pending (tests which were skipped programatically in test `it.skip()` )
4. skipped (tests which were skipped by Cypress due to error inside some hook `before() beforeEach() afterEach() after()` )

Issue: Test results with 4th state (skipped) are not reported to Qase (reporter not even recognise them as they are not logged by reporter)

**Comment by 1ivliev** [comment]
@martin-pikalek, greetings. The task is in our backlog and is already planned. We will inform you about the implementation of the new functionality and the readiness of the new version.

**Comment by 1ivliev** [comment]
@martin-pikalek Good afternoon. Please attach an example of your test case where your problem is reproduced. Thank you.
