### ISSUE TITLE
Automatic defect creation in Qase

### ISSUE THREAD

**Issue by csky-ryangibson** [qase-tms/qase-javascript#133]
Is is possible to use this tool to have a defect automatically created in Qase when an automated test fails?

I am hoping to create a TestRun that can be automatically run via Cypress.  I already have cypress talking to Qase with the cypress-qase-reporter.  I would like the results all sent to Qase, but I would also like defects to be created for any failing tests.

Stretch Goal for this little project of mine is to see if, when the defect is automatically created, if a 'send to Jira' flag can be sent so the defects are copied into my Jira instance.  (I already have my Qase instance talking to my Jira Cloud instance.)

**Comment by 1ivliev** [comment]
Hi! You can check out our roadmap or create a feature request at:
https://roadmap.qase.io

**Comment by 1ivliev** [comment]
Hi! We already have a similar request:
https://qase.canny.io/admin/board/feature-requests/p/automatic-defect-creation-in-cypress-qase-reporter
If you have any other suggestions for improvement, please tick it in our roadmap.
