### ISSUE TITLE
Qase cypress reporter is not working

### ISSUE THREAD

**Issue by tariqp193** [qase-tms/qase-javascript#134]
Hello 

For some reason, I am getting the message  `Could not send all results for 30 seconds after run. Please contact Qase Team.`

![image](https://user-images.githubusercontent.com/50297299/152413794-d2f04bf2-a690-4c46-939e-0c55dc7afe38.png)

My cypress.json configuration contains the following: 

`  "reporter": "cypress-qase-reporter",
    "reporterOptions": {
      "apiToken": "…",
      "projectCode": "DEMO",
      "runId": 1,
      "logging": true
  },`

And I am using the following commands to start my tests 
`$env:QASE_REPORT=1` and then `npx cypress run`

and I can see that I am connected to your API but upload reports failed for some reason. 

I tried to set up the project again and recheck that with some other Cypress projects but the output is the same: 

![image](https://user-images.githubusercontent.com/50297299/152413687-6e9255ef-9cb5-43da-965a-dd36a5fa8605.png)

Can you please help me to understand if I am doing something wrong?

**Comment by 1ivliev** [comment]
@tariqp193, hi! Do you, after running the command on execution, do not publish data to Qase TMS? Please describe your system environment.

**Comment by tariqp193** [comment]
Seems like this is resolved now. Thank you!
