### ISSUE TITLE
Unable to filter test case by suite_id

### ISSUE THREAD

**Issue by damarre** [qase-tms/qase-javascript#135]
i.e 
curl --request GET \
     --url 'https://api.qase.io/v1/case/<ProjectName>?suite_id=3&limit=1000&offset=0' \
     --header 'Accept: application/json' \
     --header 'Token: <ApiToken>'
     
suite_id query param doesn't work. It will show all test cases without suite_id filter

**Comment by kamilsk** [comment]
Hi! Please use `?filters[suite_id]=3`. We updated our docs before server implementation. It will be fixed this week.

**Comment by damarre** [comment]
Ok thanks!

**Comment by sklmx** [comment]
@damarre Hi! We've fixed the issue. Filters can now be used either as an array or as flat values. 
`?filters[suite_id]=3`
`?suite_id=3`

**Comment by damarre** [comment]
> @damarre Hi! We've fixed the issue. Filters can now be used either as an array or as flat values. `?filters[suite_id]=3` `?suite_id=3`

whoaa.. love it!
