### ISSUE TITLE
Gherkin steps are empty

### ISSUE THREAD

**Issue by damarre** [qase-tms/qase-javascript#149]
Hi, I tried to utilize new feature, gherkin format. But, when I checked the api response [https://api.qase.io/v1/case/{projectname}/{testcase_id}], I couldn't get the steps. It's only empty array.

![Screen Shot 2022-03-29 at 08 59 07](https://user-images.githubusercontent.com/26762943/160518996-cba47071-3ef7-4363-bc6f-27ff5398ca31.png)

**Comment by sklmx** [comment]
Hi! Currently, this option is only planned, but good news it will be implemented soon.

**Comment by damarre** [comment]
Okk.. Please keep us updated.

**Comment by sklmx** [comment]
Hi @damarre! The API now returns **gherkin** steps. The **action** property contains the entire scenario.
