### ISSUE TITLE
Create the Run with "custom_fields"

### ISSUE THREAD

**Issue by olegmingaleev** [qase-tms/qase-javascript#176]
Hello 👋

As I know, I can create run with [the custom fields](https://help.qase.io/hc/en-us/articles/360013718957-Custom-Fields) wich will be display in the run page by the web application. But this feature not allowed(or not specified) for [the create run method  by REST API ](https://developers.qase.io/reference/create-run). And I didn't find this feature for qaseio package.

Can you explain how to pass the custom fields for the create run by REST API? And I will waiting this feature for qaseio package.

**Comment by 1ivliev** [comment]
@olegmingaleev Hi! Already scheduled in the next sprint. I'll let you know when it's ready.

**Comment by 1ivliev** [comment]
@olegmingaleev Hi! We have added support for Custom Field when creating a Test Run via the API.
You can read the updated documentation:
https://developers.qase.io/reference/create-run
If you have any more questions or suggestions, please take part in making our Roadmap:
https://roadmap.qase.io
Have a great day!
