### ISSUE TITLE
Could not load reporter by name: cypress-qase-reporter

### ISSUE THREAD

**Issue by bawahakim** [qase-tms/qase-javascript#18]
Getting this error when trying to run `QASE_REPORT=1 yarn run cypress run`. 

My `cypress.json` file : 

```{
  "reporter": "cypress-qase-reporter",
  "reporterOptions": {
    "apiToken": "XXX",
    "projectCode": "IW",
    "runId": 45,
    "logging": true
  }
}
```

Following some users having similar issue, I have tried changing `reporter` to `./node_modules/cypress-qase-reporter/dist/index.jx`, it does not fix the issue. However, writing `./node_modules/cypress-qase-reporter/dist/mocha.js` actually makes the code run, but I get this error : 
```
TypeError: invalid reporter '[object Object]'{
  code: 'ERR_MOCHA_INVALID_REPORTER',
  reporter: { qase: [Function: qase] }
}
```
I have also installed `mocha` as a dev-dependency, but it also does not work.

I'm using :
``` 
"cypress": "7.0.1"
"cypress-qase-reporter": "^1.3.0"
```

**Comment by borisno2** [comment]
Any update on this? I am also getting the same error.

**Comment by zeburek** [comment]
Maybe one of you can prepare a repo with reproduction? I can't reproduce it
on my own

чт, 12 авг. 2021 г., 10:49 Josh Calder ***@***.***>:

**Comment by bawahakim** [comment]
Sorry, not working on this project anymore :/ Best of luck!

**Comment by borisno2** [comment]
Maybe an issue with Macos? I tried the same repo using a cypress docker container and it worked fine.

**Comment by zeburek** [comment]
Ok, I'll take a look on macos

пн, 16 авг. 2021 г., 04:53 Josh Calder ***@***.***>:

**Comment by evgenykochetkov** [comment]
Hello! Sorry for the delay. I investigated the issue, and it looks like the problem was in the `deasync` dependency. I will release a fix soon.

**Comment by alexandrabusu** [comment]
Any update on this?

**Comment by 1ivliev** [comment]
Fixed, please use the latest version of the reporter.
