### ISSUE TITLE
Missing dependency module "chalk" for Qase Playwright Reporter when trying to run Playwright tests

### ISSUE THREAD

**Issue by martin-pikalek** [qase-tms/qase-javascript#207]
![Screenshot 2022-05-24 at 13 38 32](https://user-images.githubusercontent.com/57229273/170027425-d955b5cd-270e-4703-8431-815725990642.png)

Package.json dependencies:
"@playwright/test": "^1.22.2"
"playwright-qase-reporter": "^1.2.0-alpha.3"

Expected: Should be able to run tests with Playwright and Playwright Qase Reporter

**Comment by 1ivliev** [comment]
@martin-pikalek Hi! Try using this assembly. Follow the instructions.
https://github.com/1ivliev/playwright-qase
Let us know if the problem persists. Have a great day!

**Comment by martin-pikalek** [comment]
@1ivliev Hello, with this assembly it was possible to run Playwright tests and report results into Qase.
However in this assembly is "chalk" dependency in package.json so it was installed regardless of needs of qase-playwright-reporter.

As user my expected solution would be: Install qase-playwright-reporter and to use it I should not need to install manually other dependencies directly (as qase-playwright-reporter should download needed dependencies for usage during installation)

**Comment by 1ivliev** [comment]
Thank you for your consideration. We have corrected this in this [PR](https://github.com/qase-tms/qase-javascript/pull/210).

**Comment by sarah-gelt** [comment]
Hi @1ivliev - I am having the same problem as the OP, but it seems like a fix for this was merged a couple of weeks ago. Has that since been released, should this still be occurring in the version I have?
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/107568761/175570207-ac9bf540-6f01-46cb-9f26-df930d16342f.png">

**Comment by martin-pikalek** [comment]
@1ivliev @sarah-gelt Hi everyone, I can confirm this issue. When trying to run tests with latest reporter, there is missing dependency error for "chalk".

"name": "playwright-qase-reporter",
"version": "v1.2.0-alpha.3",

As I am looking on package.json of playwright-qase-reporter, there is "chalk" dependency but under "devDependencies".
To be sure I also cleared my npm cache and reinstalled all dependencies.

<img width="1439" alt="Screenshot 2022-06-25 at 17 35 52" src="https://user-images.githubusercontent.com/57229273/175780580-cb80fcd6-8f34-4903-ad56-b857221a9054.png">

But when I look into package.json of reporter on GitHub (on master branch), there is "chalk" dependency under "dependencies". 

[https://github.com/qase-tms/qase-javascript/blob/master/qase-playwright/package.json](url)

Are we need to wait for new alpha version or is this just some mismatch?
