### ISSUE TITLE
Can't import RunCreate from qaseio.models

### ISSUE THREAD

**Issue by D96Fan** [qase-tms/qase-javascript#208]
I'm trying to run the following code from the ReadMe, but it seems qaseio.models isn't recognized:

```
import { QaseApi } from 'qaseio';
import { RunCreate } from 'qaseio.models';

const qase = new QaseApi("xxxxx");
const project_code='X'

const run = new RunCreate("Test run", [1, 2], { description: "some desc" })
qase.runs.createRun(project_code,run).then((res) => {
    console.log(res.data)  // RunCreated{...}
})
```

The error being:
![image](https://user-images.githubusercontent.com/34059801/170952070-56a1ba25-a82b-44c5-a4cd-d5ad42f4eafa.png)

Taking a look at the repository, there doesn't seem to be a corresponding 'models' folder, only 'model'. Am I doing something wrong?

**Comment by kmalinin** [comment]
Hi! Please use previous client version or use model.RunCreate

**Comment by D96Fan** [comment]
I've reverted to v1.5.0, which seems to be working, but I had to change the import syntax for it to succeed:
This works
``import { RunCreate } from 'qaseio/dist/src/models/index.js';``
This doesn't
``import { RunCreate } from 'qaseio.models';``
