### ISSUE TITLE
Invalid link for the demo project in README.md file.

### ISSUE THREAD

**Issue by Vazgen7788** [qase-tms/qase-javascript#215]
When clicking on the link `demo project` link opens page 404. 
<img width="1140" alt="Screen Shot 2022-06-08 at 15 54 13" src="https://user-images.githubusercontent.com/8538941/172610581-fd51c39d-6d1d-408d-9b20-1add171a511e.png">

**Comment by 1ivliev** [comment]
@Vazgen7788 Hi. Fixed in this [PR](https://github.com/qase-tms/qase-javascript/pull/217). Thank you for the feedback!
