### ISSUE TITLE
Lack of options in reporters in comparison to QaseAPI

### ISSUE THREAD

**Issue by martin-pikalek** [qase-tms/qase-javascript#216]
Hello, 

I would like to suggest to open as many as possible options to reporters as have for example createRun API endpoint options.

I know that some options could be harder to implement for reporters (for example tags, custom fields etc.) but there are some options which from my point of view just missing.

For example option: include_all_cases 

We already have option to close or not close testRun after finish but to include all cases to run, we need to create testPlan and testRun manually and attach testing framework to that specific run or create testRun via API and again to attach testing framework to that specific run. 

Reporters already have possibility to create testRuns - for undefined runId (using the same qaseAPI) but not all options from that API are propagated to user configuration of reporters.

Is it possible to include options which are not hard to implement? (as I saw, option include_all_cases is for example same as environment_id - just load variable from config and use it for createRun object if defined)

**Comment by 1ivliev** [comment]
@martin-pikalek  Hi! You can try to create a feature request to add the "create test run from test plan" functionality or add the "include_all_cases" parameter to the reporters functionality on a special page of our roadmap:
https://roadmap.qase.io
We process our requests and adapt the functionality to the requirements of our customers.

**Comment by martin-pikalek** [comment]
@1ivliev Thank you for suggestion. I did not know I can do that. So I wrote feature_request... 

https://roadmap.qase.io/feature-requests/p/cypress-qase-reporter-includeallcases-option
