### ISSUE TITLE
Gitlab CICD pipeline - CypressDockerImage - reportBulk issue with reporter

### ISSUE THREAD

**Issue by martin-pikalek** [qase-tms/qase-javascript#218]
/node_modules/cypress-qase-reporter/dist/reportBulk.js:14
const config = JSON.parse(process.env?.reporting_config);
SyntaxError: Unexpected token '.' (arrow pointing on dot before property reporting_config)

"cypress-qase-reporter": "1.4.2-alpha.2"

When I run tests locally, it seems to work, but when the same tests are running in Gitlab pipeline within official Cypress docker image - cypress/base:12 , reporting to Qase not working, leaving each test with error described on top.

I can confirm that it relates to different node versions (locally I am running node v16.14.2 and cypress/base:12 have node v12.0.0)
When I used Cypress docker image cypress/base:16.14.0 which have node v16.14.0 then reporting is functional.

If some minimal node version is required to run cypress-qase-reporter, it should be highlighted and mentioned somewhere + reporter itself should have function to check available node version in running environment and probably force some error message if running node version is below minimal node version for cypress-qase-reporter.

**Comment by 1ivliev** [comment]
@martin-pikalek Hi! We support LTS versions of Node. Thank you for your feedback, we will add information about environment requirements to our README.md
Thank you for the feedback!

**Comment by martin-pikalek** [comment]
@1ivliev Hi, thank you for answer 👍 just give you some heads up, Cypress recommended node version for docker images (tagged as latest) is cypress/base:12 (node v12.0.0). This information is available here: 

https://github.com/cypress-io/cypress-docker-images/tree/master/base

As most cypress users will do not have so much experience with analysing cypress node requirements and cypress-qase-reporter node requirements and do not even have knowledge to check their node versions on different environments, I would recommend maybe to target cypress-qase-reporter for lower node versions (for example recommended version v12.0.0) as most of cypress users will be using recommended solutions and cypress-qase-reporter is specifically made for cypress.

**Comment by 1ivliev** [comment]
Thank you for your observations. We will try to remedy the situation soon. Have a good day!
