### ISSUE TITLE
TestCafe: Timing issue with bulk update and complete run

### ISSUE THREAD

**Issue by ejerskov** [qase-tms/qase-javascript#221]
Using latest version ^1.2.0-alpha.2

Theres a timing issue when setting runComplete=true.

The run is completed before the bulk update is done, resulting in the complete hook sending a test run with 0 tests run.
This is the payload I receive:

```
{
  "event_name": "run.completed",
  "timestamp": 1655366067,
  "payload": {
    "id": 556,
    "cases": 0,
    "passed": 0,
    "failed": 0,
    "blocked": 0,
    "duration": 0
  },
    "team_member_id": 1,
    "project_code": "XXX"
}
```

And when I check app.qase.io the test run has all results.

**Comment by ejerskov** [comment]
Any news om when this will be fixed? The complete event is useless when this doesnt work :|

**Comment by sharovatov** [comment]
@ejerskov this will be fixed in around 2-3 weeks as soon as we move the core of our JS reporter to the new core which currently being tested: https://github.com/qase-tms/qase-javascript/pull/275

**Comment by ejerskov** [comment]
@sharovatov, sounds great, thanks!
