### ISSUE TITLE
Cypress: runComplete timing issue

### ISSUE THREAD

**Issue by martin-pikalek** [qase-tms/qase-javascript#228]
"cypress": "^10.1.0"
"cypress-qase-reporter": "1.4.2-alpha.2"

When I have "runComplete" feature enabled within cypress-qase-reporter QaseTestRun is completed after 1st test file (spec file), resulting in Axios errors for each another test files reports (as request for closing test run is sent with each file)

data: { status: false, errorMessage: 'Test run must be active status' }

Reporting to Qase is functional only if user have enabled "Allow to add results for cases in closed runs." within Qase project.

Expected: TestRun should be closed by reporter 1x - only after sending results of last test file.

**Comment by 1ivliev** [comment]
@martin-pikalek Hi! We already know about this cypress-qase-reporter problem. We will let you know when it is fixed.
