### ISSUE TITLE
Playwright: Error: Request failed with status code 507 on uploading results

### ISSUE THREAD

**Issue by klepik1990** [qase-tms/qase-javascript#233]
Hello! I ran into a problem loading results a few days ago. I'm getting this error due running tests (locally and in CI). But I didn't make any changes to either the tests or the playwright config. Sometime tests passed, sometimes failed because of the qase error. 
Playwright: ~1.22.0
playwright-qase-report: ^1.2.0-alpha.3

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/49123512/176618377-f96b4909-21ad-4328-89a4-2354ae7c72a9.png">

**Comment by 1ivliev** [comment]
@klepik1990  Hi! This error tells you that your workspace storage is maxed out. You can check the actual data at the link:
https://app.qase.io/workspace/attachments

**Comment by klepik1990** [comment]
ooops, thanks a lot, that's a reason

**Comment by 1ivliev** [comment]
We have updated our documentation:
https://developers.qase.io/docs
Thank you for the request!
