### ISSUE TITLE
cypress-qase-reporter: Sometimes test results are sent, sometimes not.

### ISSUE THREAD

**Issue by MakoCagay** [qase-tms/qase-javascript#234]
"cypress": "^9.6.1"
"cypress-qase-reporter": "^1.4.2-alpha.2"

Even when the same test case is used, sometimes the test results are sent and sometimes not.

Test results are sent:
<img width="1258" alt="results1" src="https://user-images.githubusercontent.com/89907960/177284075-5b6dbad5-597f-441d-acae-499739fa3fb5.png">

Test results are not sent:
<img width="566" alt="results2" src="https://user-images.githubusercontent.com/89907960/177284151-3891e36e-b4b2-4a86-8290-e29b12bbedc3.png">

**Comment by widiariayyu** [comment]
i experienced this issue too, my current workaround is downgrade the dependencies to 1.4.1 and its worked

**Comment by sasha-t** [comment]
```
"cypress": "8.0.0"
"cypress-qase-reporter": "1.4.2-alpha.2"
```

I have the same problem.
downgrading the reporter dependency to 1.4.1 doesn't help me.

**Comment by nafernandafw** [comment]
I also have the same problem

**Comment by CaiqueCoelho** [comment]
I'm having the same problem and I describe better here #354 https://github.com/qase-tms/qase-javascript/issues/354
