### ISSUE TITLE
[QUESTION] Do "playwright-qase-reporter" have steps in report?

### ISSUE THREAD

**Issue by Belisckner** [qase-tms/qase-javascript#235]
Hi 👋

Currently, I try playwright-qase-reporter and it's awesome, thanks for that!

But, do you have plan to add "step" from playwright report? 
All cases that created by "playwright-qase-reporter" in QASE project are empty (only have title from test case)

**Comment by 1ivliev** [comment]
Hi! You can check out our roadmap or create a feature request at:
https://roadmap.qase.io/

**Comment by Belisckner** [comment]
Thanks, I created an feature request https://roadmap.qase.io/feature-requests/p/add-step-in-playwright-qase-reporter

**Comment by Belisckner** [comment]
h

**Comment by Verm1n** [comment]
hi, the question is actual

**Comment by YonKu0** [comment]
Is this feature available?
