### ISSUE TITLE
Many methods not available in qase-javascript, such as qase.runs.get

### ISSUE THREAD

**Issue by jamesmortensen** [qase-tms/qase-javascript#245]
I installed qase-javascript 2.0.1 via `npm install qaseio` and setup the following test file:

main.js
```
const qaseio = require( 'qaseio');
require('dotenv').config()

const qase = new qaseio.QaseApi(process.env.QASE_TOKEN);

qase.runs.get("DP", 1).then((res) => {
    console.log(res.data)  // RunInfo{...}
})
```

But when running it, it seems the get method is not available:

```
TypeError: qase.runs.get is not a function
    at Object.<anonymous> (/Users/james/Dev/full-projects/james-sandbox/qase-reporter/main.js:8:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

I tried both using CommonJS and ESM, and both result in the same behavior.  I also was not able to call qase.projects.get as well.  Not sure what the problem is, but from what I can tell, I believe I am following the instructions in the documentation:  https://www.npmjs.com/package/qaseio.  

I'm using node 16.15.1 on Mac m1, if it matters...

**Comment by jamesmortensen** [comment]
I was wondering if there's any workaround to the issues I'm facing.  I tried the older 1.5.0 version, and I'm not able to get it working either.

**Comment by jamesmortensen** [comment]
Correction, 1.5.0 works for me.  I just confirmed on v1.5.0 I can fetch test run data without issue on Nodejs 14,16, and 18.  I have confirmed that it does not work with the same code when installing qaseio@2.0.1, 2.0.0, 2.0.0-alpha.5, and 2.0.0-alpha.0.  Hope this helps!

**Comment by jamesmortensen** [comment]
Is this an official Qase repository or a community thing?  Can any maintainers weigh in on this?  The most recent version of your library doesn't work.  Should I be using something else instead of this library?

**Comment by sharovatov** [comment]
@jamesmortensen thanks for your report. This is an official Qase repository and I'm sorry you had this experience so far.

We are currently rebuilding the core of our Qase JS reporter functionality here : https://github.com/qase-tms/qase-javascript/ (I've replied you there once too), and as soon as we're done (and we're nearly there) we will have all the issue fixed there.

Once again, sorry for the inconvenience, we're pushing hard to make it right now :(

**Comment by jamesmortensen** [comment]
Hi @n3r can you please explain or update on the status of Qase 2.0.1?  Our teams are writing their own API wrappers instead of using this.  How should we proceed?  Thank you!
