### ISSUE TITLE
Failed to publish "Failed" test Playwright-Qase Integration

### ISSUE THREAD

**Issue by chalvjulian** [qase-tms/qase-javascript#269]
Hii all,

I have an issue about publish report to Qase from Playwright using API and i get **freeze**.
I just want to publish a "**Failed**" test that i modify.
I don't know what happens to me.
For your information, i just run "**Passed**" & "**Skip**" tests and its work normally.
It's awesome.

Please, give me some idea for solving my problem

![Screenshot_10](https://user-images.githubusercontent.com/53189284/184102126-e2c4fc8f-a436-447b-8d9c-5751a99b6a11.png)

![Screenshot_11](https://user-images.githubusercontent.com/53189284/184101722-77865b2f-53a0-40b0-b005-3012d72a1b01.png)

**Comment by 1ivliev** [comment]
@chalvjulian Hi. Please attach an example of a test that should be reported with the status "failed".
