### ISSUE TITLE
Cypress and Cucumber: qase report using both with cypress-cucumber-preprocessor

### ISSUE THREAD

**Issue by vmalvaro** [qase-tms/qase-javascript#272]
I'm using https://www.npmjs.com/package/cypress-cucumber-preprocessor, to use cucumber within Cypress. 

I tried to make the automated report work with https://www.npmjs.com/package/cucumberjs-qase-reporter without luck so far.

Did someone manage to make it work? I'd appreciate it if someone can guide me or share some of the configs about this.

Thanks!

**Comment by sharovatov** [comment]
hey @vmalvaro 

at the moment we don't have a way to integrate qase with cypress cucumber module, but we're planning to have it later (around 1-2 months from now).

If you have time, you can get some inspiration from here: https://github.com/1ivliev/playwright-cucumber-qaseio — this is our unofficial playwright cucumber module — and build your own. 

Thanks!

**Comment by cristian-halita-thinslices** [comment]
> at the moment we don't have a way to integrate qase with cypress cucumber module, but we're planning to have it later (around 1-2 months from now).

Any updates on this after 5 months?
