### ISSUE TITLE
[qase-core-reporter] Error in examples jest/cypress after install dependency 

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-javascript#280]
STR:
- install dependency in root for example jest/cypress from https://github.com/qase-tms/qase-javascript/pull/275

AR:

![image](https://user-images.githubusercontent.com/64368690/188956559-263997e3-8092-4d1f-b566-3121eb3f7538.png)
[report.txt](https://github.com/qase-tms/qase-javascript/files/9508920/report.txt)

ER:
- it's works well for another examples (testcafe/playwright/cucumberjs/newman) but not work for jest/cypress

**Comment by 1ivliev** [comment]
@dimitriharding

**Comment by dimitriharding** [comment]
@1ivliev These are now resolved. 

The issue was that the modules were self-referencing themselves and that caused that weird peer error to be throw.

**Comment by 1ivliev** [comment]
Thank you, the problem is fixed.
