### ISSUE TITLE
[qase-core-reporter] Update version sub reporters 

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-javascript#281]
Need update version reporters for sub reporters in https://github.com/qase-tms/qase-javascript/pull/275
- `cucumberjs-qase-reporter` (last version form npm - 0.2.8-alpha.1)
- `cypress-qase-reporter` (last version form npm - 1.4.2-alpha.2)
- `jest-qase-reporter` (last version form npm - 1.3.0-alpha.4)
- `Newman-reporter-qase` (last version form npm - 1.0.6-alpha.2)
- `playwright-qase-reporter` (last version form npm - 1.2.0-alpha.3)
- `testcafe-reporter-qase` (last version form npm - 1.2.0-alpha.2)

**Comment by 1ivliev** [comment]
@dimitriharding

**Comment by dimitriharding** [comment]
@1ivliev This should be resolved now.
