### ISSUE TITLE
[qase-core-reporter] Incorrect header information

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-javascript#285]
@dimitriharding Hi, can you check the data transfer in the header?

1. it is necessary to update the major version in the reporters
2. it is necessary to set Qase-core-reporter version `1.0.0` in header information
3. you need to keep the old reporter names in the X-CLIENT block. 
4. it is necessary to check the transfer of header at `playwright`, `newman`, `cucumber`

Now:
- playwright (broken name, framework and reporter versions, need update major version)
<img width="590" alt="image" src="https://user-images.githubusercontent.com/64368690/189642526-7674bad5-ce78-4c47-9ca3-1ff8be533086.png">

- cypress (broken name, reporter version, need update major version)
<img width="589" alt="image" src="https://user-images.githubusercontent.com/64368690/189657303-ce43ac36-5e54-46ca-93a0-402ef8562ddb.png">

- newman (broken name, reporter version, need update major version)
<img width="591" alt="image" src="https://user-images.githubusercontent.com/64368690/189648809-7fdd5356-3322-4bf0-b2c9-906843f922be.png">

- jest (broken name, need update major version)
<img width="592" alt="image" src="https://user-images.githubusercontent.com/64368690/189648969-9eb626c5-37f6-4277-81c0-1a020cff0417.png">

- testcafe (broken name, version, need update major version)
<img width="592" alt="image" src="https://user-images.githubusercontent.com/64368690/189657120-68503ecc-97dc-460f-a0c0-a6b5447a6f62.png">

- cucumber (broken name framework and reporter, reporter version, need update major version)
<img width="589" alt="image" src="https://user-images.githubusercontent.com/64368690/189649323-f9acf519-41de-4dac-9caa-073f9159379c.png">

Before:

- playwright
<img width="591" alt="image" src="https://user-images.githubusercontent.com/64368690/189654973-1ea8f7df-02b4-455d-89b0-ffda1d4a764f.png">

- testcafe
<img width="593" alt="image" src="https://user-images.githubusercontent.com/64368690/189655602-4136c5fe-0f21-46e9-8074-80060e0f6464.png">

- newman
<img width="592" alt="image" src="https://user-images.githubusercontent.com/64368690/189656357-c9688b59-0286-49c8-b54c-28f9f6abf20a.png">

- jest
<img width="591" alt="image" src="https://user-images.githubusercontent.com/64368690/189658242-316bfecd-c500-4ee2-b0b6-7603c893869b.png">

- cypress
<img width="589" alt="image" src="https://user-images.githubusercontent.com/64368690/189658576-af418f7f-4313-4631-a63f-0ad4398d4656.png">

- cucumber
<img width="591" alt="image" src="https://user-images.githubusercontent.com/64368690/189659103-cbc58bbf-1589-4685-b855-ad3aaaa5a902.png">

**Comment by dimitriharding** [comment]
@1ivliev This should be resolved now.

**Comment by 1ivliev** [comment]
Yep, this is resolved. It works well now. But there is still a issue with updating the versions of the reporters themselves. Do you think we can update the major version before release?
Example:
`qase-cucumberjs=v0.2.8-alpha.1` -> `qase-cucumberjs=v0.3.0`
or
`qase-cucumberjs=v0.2.8-alpha.1` -> `qase-cucumberjs=v0.3.0-alpha.1`
@sharovatov 

- playwright
<img width="590" alt="image" src="https://user-images.githubusercontent.com/64368690/189850778-699a541c-3dbf-4fa7-8faa-dbcd3b9b290a.png">

- cypress
<img width="591" alt="image" src="https://user-images.githubusercontent.com/64368690/189850909-0c7ccb22-4a9b-4afb-8fd2-9a0631fac120.png">

- newman
<img width="591" alt="image" src="https://user-images.githubusercontent.com/64368690/189851018-2df36b46-b44c-440f-b3c4-d939c59be4c5.png">

- jest
<img width="593" alt="image" src="https://user-images.githubusercontent.com/64368690/189851118-42a5dfc7-fd8b-4af7-beef-424e26c4dfc6.png">

- testcafe
<img width="591" alt="image" src="https://user-images.githubusercontent.com/64368690/189851205-e29ac0e8-e45c-4dbd-b401-24ebc624ef2a.png">

- cucumber
<img width="589" alt="image" src="https://user-images.githubusercontent.com/64368690/189851289-55aae339-2a22-4485-a86d-a8aedc5f9418.png">

**Comment by sharovatov** [comment]
I think we certainly need to bump the major version when we release.

@dimitriharding what do you think?

**Comment by dimitriharding** [comment]
Yes, we can publish `qase-core-reporter@1.0.0` first, and then update the reporters to use the core module and publish those using a major version after.
