### ISSUE TITLE
[qase-core-reporter] Different value names in Environment Options

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-javascript#287]
@dimitriharding,
Hi! I found one more thing. Please take a look at it. It's different Environment Options.
CucumberJS:
- formerly `QASE_ENABLED` and now `QASE_REPORT` (as in other reporters and qase-core-reporter)
- formerly `QASE_PROJECT`, and now `QASE_PROJECT_CODE` (as in other reporters and qase-core-reporter)

Cypress:
- formerly `QASE_SCREENSHOT_SENDING`, now `QASE_UPLOAD_ATTACHMENTS` (as in other reporters and qase-core-reporter)

TestCafe:
- formerly `QASE_ENABLED` and now `QASE_REPORT` (as in other reporters and qase-core-reporter)
- formerly `QASE_PROJECT` and now `QASE_PROJECT_CODE` (as in other reporters and qase-core-reporter)

Can we support all versions of input Environment Options?

**Comment by dimitriharding** [comment]
The followings were resolved in #288 

> CucumberJS:
> - formerly QASE_ENABLED and now QASE_REPORT (as in other reporters and qase-core-reporter) 

> Cypress:
> - formerly QASE_SCREENSHOT_SENDING, now QASE_UPLOAD_ATTACHMENTS (as in other reporters and qase-core-reporter)

> TestCafe:
> - formerly QASE_ENABLED and now QASE_REPORT (as in other reporters and qase-core-reporter)

---

Everything else should also be resolved now.

Please also rebuild the core module when checking.

**Comment by 1ivliev** [comment]
@dimitriharding 
Thank you, it works perfectly!
