### ISSUE TITLE
[qase-core-reporter] Different value names in Config

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-javascript#288]
@dimitriharding,
Hi! I found one more thing. Please take a look at it. This applies to configuration files for reporters.

CucumberJS:
- formerly `enabled` and now `report` (as in other reporters and qase-core-reporter).

Cypress:
- formerly `sendScreenshot` and now `uploadAttachments` (as in other reporters and qase-core-reporter).

TestCafe:
- formerly `enabled` and now `report` (as in other reporters and qase-core-reporter).

Can we support all versions of input Config? What do you think about this?

**Comment by dimitriharding** [comment]
@1ivliev Sure, we can make these backward compatible. I was thinking that maybe we could introduce these as breaking changes in the major version release to ensure that there is a standard across all modules.

But I do agree this could be an issue for users so I will make the update. 

**Cypess**: This can be accommodated from the cypress-reporter level
**CucumberJS & TestCafe:** These will require a small update in the code-module to account for `enabled` as well.

**Comment by dimitriharding** [comment]
@1ivliev This should be resolved now. 

When checking, please rebuild the core reporter and the reporters mentioned in this issue.

**Comment by 1ivliev** [comment]
Thank you, it works great!
