### ISSUE TITLE
[qase-core-reporter] Adding information message in console

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-javascript#290]
When installing an updated version of the reporters:
- `cucumberjs-qase-reporter`
- `cypress-qase-reporter`
- `newman-reporter-qase`
- `jest-qase-reporter`
- `playwright-qase-reporter`
- `testcafe-reporter-qase`

from the npm (or source), needed to output in the console information about what you need to install additionally - `qase-core-reporter`. This module is mandatory for all reporters.

**Comment by dimitriharding** [comment]
Once the `qase-core-reporter` is published, all updated versions of the reporters will have the core reporter as a dependency by default, so no need for the user/client to install or build from the source. 

Currently, it is being referenced by a path, but it will be referenced by npm.

We can still keep this ticket open to confirm once all updated versions are published.

**Comment by 1ivliev** [comment]
Hi, thanks!
