### ISSUE TITLE
[playwright-qase-reporter] Flaky "No such file or directory" error on failed tests

### ISSUE THREAD

**Issue by klepik1990** [qase-tms/qase-javascript#295]
Hello guys! Sometimes my CI build fails because I get such error. Sometimes screenshots of failed tests upload correctly, but sometime build fails. https://prnt.sc/3NJPE-VPwyDT
I use 
    "playwright-qase-reporter": "1.1.3"
    "@playwright/test": "~1.27.0",

**Comment by loxinchi** [comment]
@n3r Could you re-open this issue?
I encountered this in github actions runner twice today.
```
    "@playwright/test": "^1.31.1",
    "playwright-qase-reporter": "^1.2.0-alpha.3",
```

**Comment by hex0cter** [comment]
+1

**Comment by n3r** [comment]
I'm trying to reproduce that right now.

**Comment by hex0cter** [comment]
Any progress? It is still happening from time to time.

**Comment by artamonovs** [comment]
@n3r Can you take a look, please?

**Comment by artamonovs** [comment]
@n3r sorry, for bothering you, but can you push this bug into a development, please?
