### ISSUE TITLE
Qase Cypress integration does not work

### ISSUE THREAD

**Issue by felixphilipk** [qase-tms/qase-javascript#321]
The cypress config for qase is not integrating

**Comment by 1ivliev** [comment]
@felixphilipk, hi! Can you provide a little bit more information for us?

**Comment by felixphilipk** [comment]
The config for QASE was defined but was unable to view the results after the run the QASE test id was also linked 


const { defineConfig } = require("cypress");



module.exports = defineConfig({

  reporter: 'cypress-qase-reporter',
    reporterOptions: {
      reporterEnabled: 'cypress-qase-reporter',
      ReporterOptions: {
        apiToken: 'xxxxxa5de976715e292294c137axxxxxxxx',
        projectCode: 'xx',
        logging: true,
        basePath: 'https://api.qase.io/v1',
        screenshotFolder: 'screenshots',
        sendScreenshot: true,
        runComplete: true,
        
       
      },
    },

 
  
  e2e: {
    setupNodeEvents(on, config) {
      // e2e testing node events setup code

      baseUrl : 'https://app.staging.intempt.com/home'
    
    },
    pageLoadTimeout: 100000,
    defaultCommandTimeout: 20000,
    execTimeout: 60000,
    requestTimeout: 60000,
    responseTimeout: 60000,
    taskTimeout: 60000,
    chromeWebSecurity : false,
    video : false,
    projectId : "9kghep",
    retries : 0,
    viewportWidth : 1440,
    viewportHeight : 823,
    failOnStatusCode : false,
    //experimentalWebKitSupport: true,
    experimentalSessionAndOrigin:true,
    
   
  
    
   
  }



 



});

**Comment by 1ivliev** [comment]
Please show the stdout. What command do you start the reporter with?

**Comment by felixphilipk** [comment]
![Screenshot 2022-12-02 at 6 53 47 PM](https://user-images.githubusercontent.com/23369939/205303181-735deab8-0e22-4a76-81e4-ce6fa21e885c.png)

**Comment by felixphilipk** [comment]
![Screenshot 2022-12-02 at 6 54 05 PM](https://user-images.githubusercontent.com/23369939/205303240-bff3944d-a90d-4d82-9cce-cf907634e0f8.png)

**Comment by tcarlson516** [comment]
Hello, i am also experiencing a bug from my end. I am trying to integrate cypress with qase and was able to have the run show up on qase but the test case that i would like to show the result is not appearing. I have attached screenshots on how i set up my config file, test case, etc.
<img width="1118" alt="Screenshot 2022-12-09 at 12 01 06 PM" src="https://user-images.githubusercontent.com/120368880/206999235-0ddd2fdc-b36f-48a1-9854-186b79d523ae.png">
<img width="543" alt="Screenshot 2022-12-09 at 12 01 36 PM" src="https://user-images.githubusercontent.com/120368880/206999238-273c0e47-883a-4568-9a1e-ebd14af24ace.png">
<img width="761" alt="Screenshot 2022-12-09 at 12 01 51 PM" src="https://user-images.githubusercontent.com/120368880/206999242-6f965a65-6496-475b-ac4e-ac38051dca08.png">
<img width="373" alt="Screenshot 2022-12-09 at 12 02 10 PM" src="https://user-images.githubusercontent.com/120368880/206999244-c2e61a3a-d74f-44da-af94-e9ee78bbb4a1.png">
<img width="811" alt="Screenshot 2022-12-09 at 12 05 41 PM" src="https://user-images.githubusercontent.com/120368880/206999287-761e39a5-efae-4d60-bfb7-9929e19ee11c.png">
