### ISSUE TITLE
Playwright E2E: Some test cases are failing when QASE reporter is enabled in test run

### ISSUE THREAD

**Issue by neilmatillano** [qase-tms/qase-javascript#368]
In playwright E2E tests, some tests are failing when it's run with QASE reporter enabled but all tests passed when running without it.

Results when QASE reporter is enabled : https://app.qase.io/public/report/0acdf0c4ce552cef30401ab7db7386d14a6c6c93
Results when QASE reporter is disabled:
![Screenshot 2023-02-16 at 13 32 52](https://user-images.githubusercontent.com/4159492/219366020-adb1d0e8-e1f6-4b86-bead-0b56f89351cf.png)

Here's the console logs for the failing tests results with QASE reporter:
---------------------------------------------------------
e2e-tests git:(main) ✗ QASE_REPORT=1 npx playwright test
qase: Current PID: 84532
qase: Project HH exists
qase: Using run 43 to publish test results
qase: Test should create page passed
qase: Result prepared for publish: should create page 
qase: Test should create blog app passed
qase: Result prepared for publish: should create blog app 
qase: Test should show the global search mfe passed
qase: Result prepared for publish: should show the global search mfe 
qase: Test should create timeline item passed
qase: Result prepared for publish: should create timeline item 
qase: Test should like a post passed
qase: Result prepared for publish: should like a post 
qase: Test should comment a post passed
qase: Result prepared for publish: should comment a post 
qase: Test should add emojis via emoji picker passed
qase: Result prepared for publish: should add emojis via emoji picker 
qase: Test should upload a file as an attachment passed
qase: Result prepared for publish: should upload a file as an attachment 
qase: Test should share a post passed
qase: Result prepared for publish: should share a post 
qase: Test should create restricted post passed
qase: Result prepared for publish: should create restricted post 
qase: Test should load timeline items created by subscribed users passed
qase: Result prepared for publish: should load timeline items created by subscribed users 
qase: undefined
qase: Result prepared for publish: should create items for sender 
qase: undefined
qase: Result prepared for publish: should delete timeline item 
qase: undefined
qase: Result prepared for publish: should create items for sender 
qase: Test should delete timeline item passed
qase: Result prepared for publish: should delete timeline item 
qase: undefined
qase: Result prepared for publish: should have stickys on top 
qase: undefined
qase: Result prepared for publish: should login 
qase: undefined
qase: Result prepared for publish: Should search for a community:  
qase: Test Should search for a timeline post:  skipped
qase: Result prepared for publish: Should search for a timeline post:  
qase: undefined
qase: Result prepared for publish: should login 
qase: undefined
qase: Result prepared for publish: Should search for a community:  
qase: Test Should search for a page:  passed
qase: Result prepared for publish: Should search for a page:  
qase: Test Should search for user by name:  passed
qase: Result prepared for publish: Should search for user by name:  
qase: Test should have stickys on top passed
qase: Result prepared for publish: should have stickys on top 
qase: Test Should search for user by department:  passed
qase: Result prepared for publish: Should search for user by department:  
qase: Test Should search for user by email:  passed
qase: Result prepared for publish: Should search for user by email:  
qase: Test Should search for user by location:  passed
qase: Result prepared for publish: Should search for user by location:  
qase: Test Should search for user by jobtitle:  passed
qase: Result prepared for publish: Should search for user by jobtitle:  
qase: 28 result(s) sent to Qase
qase: Run 43 completed
qase: https://app.qase.io/run/HH/dashboard/43
---------------------------------------------------------

**Comment by sklmx** [comment]
Hi @neilmatillano! As I see, tests are failing because of the timeout.
https://app.qase.io/public/report/0acdf0c4ce552cef30401ab7db7386d14a6c6c93/668c41e56f06e14b564fba949cf5bbcdd7c574a8
