### ISSUE TITLE
Qase_report=1 shows QASE_REPORT=1' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Vruttikap** [qase-tms/qase-javascript#370]
When I run qase_report , it shows > QASE_REPORT=1 npx cypress run

'QASE_REPORT' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sklmx** [comment]
Hi @Vruttikap! In case you're using Windows, try setting environment with the **set** command

**Comment by Vruttikap** [comment]
It did not work

**Comment by Vruttikap** [comment]
![image](https://user-images.githubusercontent.com/126106262/220994667-8da9fbfc-526d-42ae-aee3-5e3c7f2b3fd6.png)

**Comment by n3r** [comment]
I assume that you are using Windows CommandLine. So `QASE_REPORT=1` is a command that defines environment variable `QASE_REPORT` and sets its value to 1.

On Windows, you can use the following command: `set QASE_REPORT=1 && npx cypress run` or:
```set QASE_REPORT=1
npx cypress run```
