### ISSUE TITLE
Run completition fails with 400

### ISSUE THREAD

**Issue by RB-Lab** [qase-tms/qase-javascript#372]
Hello,
I am running a `cypress-qase-reporter` `1.4.2-alpha.2` with cypress 12.7.0 (although I had the same issue with v10 as well). I have set `"runComplete": true` along with "Allow to add results for cases in closed runs", as it is said in doc. And reporting seems fine, however I have my logs filled with **extremely long** errors, showing the whole internals of axios requests. Error (`Error till publishing Error: Request failed with status code 400`) happens on `https://api.qase.io/v1/run/XXX/XX/complete` request, the payload is `{ status: false, errorMessage: 'Test run must be active status' }`.

Switching to 1.4.1 fixes the issue but runs also do not complete in this case (I guess this feature only appeared in 1.4.2-alpha.2).

**Comment by n3r** [comment]
Hello @RB-Lab!

We are going to fix this issue on the backend. It seems, that you have faced a race condition. So, when you try to complete "completed" run, you won't get an error.
