### ISSUE TITLE
[qase-playwright-v1.2.0-alpha.5] Error: Request failed with status code 400

### ISSUE THREAD

**Issue by anywheresebzaj** [qase-tms/qase-javascript#389]
Is there any possibility of not including some tests/setups in the reports? I intentionally didn't add `qase()` in the test describe but at the end of the CI job, I am getting the error. Apart from that there are also two typos "Erorr" and "Erorrs". 
`qase: Unable to send results into Qase. Error: Request failed with status code 400
qase: Erorr message: Data is invalid.
qase: Erorrs: [{"field":"results.0.case_id","error":"The results.0.case_id field is required."},{"field":"results.1.case_id","error":"The results.1.case_id field is required."},{"field":"results.2.case_id","error":"The results.2.case_id field is required."},{"field":"results.3.case_id","error":"The results.3.case_id field is required."},{"field":"results.4.case_id","error":"The results.4.case_id field is required."},{"field":"results.5.case_id","error":"The results.5.case_id field is required."},{"field":"results.7.case_id","error":"The results.7.case_id field is required."}]`

**Comment by har16o** [comment]
I also have the same problem

**Comment by hex0cter** [comment]
Same error with `1.2.1`:
```
qase: Unable to send results into Qase. Error: Request failed with status code 400
qase: Erorr message: Data is invalid.
qase: Erorrs: [{"field":"results.0.case_id","error":"The case id field is required."},{"field":"results.0","error":"Invalid step result definition."},{"field":"results.1.case_id","error":"The case id field is required."},{"field":"results.1","error":"Invalid step result definition."}]
```
Only happened to one of the two projects though.

**Comment by hex0cter** [comment]
It turned out I only needed to turn on the `Auto create test case` option in project settings:
<img width="677" alt="image" src="https://github.com/qase-tms/qase-javascript/assets/9008480/31834e60-4102-4e45-ac6d-8fb1b1a27f3e">

**Comment by hvitis** [comment]
> It turned out I only needed to turn on the `Auto create test case` option in project settings: <img alt="image" width="677" src="https://user-images.githubusercontent.com/9008480/262677166-31834e60-4102-4e45-ac6d-8fb1b1a27f3e.png">

You also need to specify the environmentId and / or create it manually in the dashboard if it does not exist.

**Comment by hvitis** [comment]
Opened [PR](https://github.com/qase-tms/qase-javascript/pull/444) to fix this missinformation.

**Comment by shzawa** [comment]
I'm also encountering the same issue. 
My idea is to send reports in a phased manner. Specifically, I intend to include only those test scenarios from the code I've created that are invoking `qase(caseId)` in the report. 
In Qase, I prefer to have only the test cases that are manually created, thus I would appreciate it if a solution could be found that does not involve enabling `Auto create test case` as much as possible.

**Comment by dc7290** [comment]
@shzawa 

I am in the same situation, only QaseIDs are tied to test cases that have been created in advance in Qase and are secured in Playwright.
Therefore, I do not want unintended test cases to be created in Qase, but I have taken the following as an alternative that can be done in the current situation. Please refer to them if you like. 1.

1. create a Suite in Qase's Repository that says "Tests done only in Playwright".
2. set up the following in Playwright's configuration

```js
{
...
  reporter: [
    ['html'],
    [
      'playwright-qase-reporter',
      {
        projectCode: 'projectCode',
        rootSuiteTitle: 'Playwrightでのみ行なっているテスト',
      },
    ],
  ],
...
}
```

This way, the Qase test cases automatically created from Playwright are all in one place, so we have adopted this as a compromise.

<日本語>

私も同じ状況で、あらかじめ作成したQaseのテストケースのうち、Playwrightで担保できているテストケースのみQaseIDを紐づけています。
そのため、意図しないテストケースがQaseに作成されることは望まないのですが、現状でできる代替案として以下を取りました。よろしければ参考にしてください。

1. QaseのRepositoryに「Playwrightでのみ行なっているテスト」といったSuiteを作成する
2. Playwrightの設定で以下のように設定する

```js
{
...
  reporter: [
    ['html'],
    [
      'playwright-qase-reporter',
      {
        projectCode: 'projectCode',
        rootSuiteTitle: 'Playwrightでのみ行なっているテスト',
      },
    ],
  ],
...
}
```

このようにすることで、Playwrightから自動的に作成されるQaseのテストケースは1箇所にはまとまるので、妥協案として採用しています。

**Comment by NickVolynkin** [comment]
Now you can remove specific test from Qase report by marking them with `qase.ignore()`:

```javascript
  test('Running, but not reported to Qase', () => {
    qase.ignore();
    expect(true).toBe(true);
  });
```

It was introduced in qase-playwright 2.0.2. See the upgrade guide: https://github.com/qase-tms/qase-javascript/tree/main/qase-playwright#updating-from-v1

Resolved in commit https://github.com/qase-tms/qase-javascript/commit/a24fb36f4a4bf91dc63622929c853a0a30e1325c

**Comment by NickVolynkin** [comment]
> Specifically, I intend to include only those test scenarios from the code I've created that are invoking qase(caseId) in the report.

@shzawa it's an interesting idea, thank you for suggesting. As I understand, you're starting with an existing codebase of autotests and would like to explicitly include tests in a Qase report, rather than exclude them with something like `qase.ignore()`. Could you please explain why you prefer it this way? It will help me better understand the problem and design a better solution.

**Comment by shzawa** [comment]
@NickVolynkin 
Thanks for your interest!
At the time of my submission to this issue, the team I was on had the following request.

1. Include test cases created manually by QAE and test cases created by automated tests in the same project. (Because we want to treat manual and automated tests in the same project.)
2. We want to include in the project only those test cases created by automated testing that have been agreed upon by the QAE. (To ensure the quality of the test cases themselves.)
3. Existing automated tests have a large volume of test cases. Many of them are lined up that QAE does not have a grasp of.

I believe that this problem can be solved by using a mechanism such as `qase.ignore()` to suppress report sending on the code base, without using the technique I mentioned above!
