### ISSUE TITLE
Specify environment for new created test run

### ISSUE THREAD

**Issue by yetithefoot** [qase-tms/qase-javascript#42]
I'm using the jest reporter to create new test runs to track my UI tests. 

I see that [API provides environment_id param](https://developers.qase.io/#create-a-new-test-run), I'd like to specify. However, I find no way how the reporter picks this up.

It would be great that the TestRun is marked with a specific environment.
Thanks!

**Comment by evgenykochetkov** [comment]
Hi! I implemented this in v1.2.0, please update and try it out!
BTW, we should probably show environment IDs somewhere in the UI 😀
