### ISSUE TITLE
[playwright-qase-reporter v1.2.1] No error if the token is invalid or missed

### ISSUE THREAD

**Issue by VinkotovUULA** [qase-tms/qase-javascript#445]
### Issue with playwright-qase-reporter v1.2.1: Unclear Logging for API Token Issues

**Configuration:**

I have set QASE_REPORT to 'true'.
I have set QASE_LOGGIN to 'true'.

**Problem Description:**
When the API token is either missing or invalid, the expected behavior is to receive a clear error indicating that the token is either absent or incorrect. However, the current behavior is that the reporter remains silent and provides no feedback. This made troubleshooting difficult because I initially believed I had set the QASE_REPORT variable incorrectly.

**Recommendation:**
For enhanced user experience and easier troubleshooting, please consider adding more explicit logs for failed API requests, especially when there's an issue with the API token. If, by any chance, this issue stems from my configuration and not the library itself, I would appreciate guidance on setting up the logger correctly.

Thank you for your attention to this matter.

**Comment by NickVolynkin** [comment]
Need to check if it still happens in v2
