### ISSUE TITLE
[playwright-qase-reporter] Mitigation of Axios Cross-Site Request Forgery Vulnerability in playwright-qase-reporter npm package

### ISSUE THREAD

**Issue by bs-rezve** [qase-tms/qase-javascript#475]
The npm package "playwright-qase-reporter" is currently vulnerable to a moderate Cross-Site Request Forgery (CSRF) issue in the Axios library, as identified by the npm audit advisory [GHSA-wf5p-g6vw-rhxx](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx).

## Vulnerability Details

  Severity: Moderate
  Package: axios
  Patched Version: >=1.6.0
  Dependency Chain: playwright-qase-reporter > qaseio > axios
  Advisory Link: [GHSA-wf5p-g6vw-rhxx](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx)

![image](https://github.com/qase-tms/qase-javascript/assets/47731427/9a65b352-80a7-4f0c-8e7e-23580ba4e2cd)

## Recommendation:
Update the Axios library in the "playwright-qase-reporter" npm package to version >=1.6.0 to mitigate the CSRF vulnerability.

## Steps to Reproduce:
The vulnerability can be verified by running the npm audit command on the "playwright-qase-reporter" npm package.

Thanks

**Comment by apis3445** [comment]
Any updates?
