### ISSUE TITLE
[playwright-qase-reporter] Feature Request: Real-Time Test Result Updates

### ISSUE THREAD

**Issue by rymbekov** [qase-tms/qase-javascript#524]
**Description:**

Currently, the `playwright-qase-reporter` requires users to wait for all test runs to finish before seeing the results in Qase. This delay can impact productivity and make it challenging to monitor test progress in real-time. I'm requesting a feature that provides real-time updates of test results within Qase as tests are executed.

**Use Cases:**

- QA teams need to monitor test progress in real-time during test execution.
- Developers want immediate feedback on test failures to expedite the debugging process.

**Benefits:**

- Improved visibility into test progress and results.
- Faster identification and resolution of test failures.
- Enhanced collaboration among team members during testing.

**Comment by gibiw** [comment]
@rymbekov  thanks for noticing! Try to update the qase-playwright reporter to 2.0.3. You can find more details [here](https://github.com/qase-tms/qase-javascript/tree/main/qase-playwright#updating-from-v1)
