### ISSUE TITLE
Does playwright-qase-reporter support different reports for different browsers? 

### ISSUE THREAD

**Issue by saysetel** [qase-tms/qase-javascript#527]
Good day.
Thank you for playwright-qase-reporter, love to use this! 
I'm curious, is there any way to generate separate test runs for each browser? 
I run tests on chromium and WebKit.
For now, when I use "QASE_REPORT=1 yarn playwright test" it generates one test run in Qase, where each test case has a "retest" status for each browser. 
<img width="534" alt="image" src="https://github.com/qase-tms/qase-javascript/assets/96988483/7b944be9-6b50-42a0-881d-61e419f749d4">

Would be great if there option to create two separate runs, for chromium and for WebKit, for example, instead of one.

**Comment by NickVolynkin** [comment]
Hey, @saysetel!

The easiest way to achieve this is to run Playwright multiple times, with a different browser each time:

```bash
QASE_REPORT=1 yarn playwright test --browser chrome
QASE_REPORT=1 yarn playwright test --browser firefox
```

See https://playwright.dev/docs/test-cli#reference for the reference. This way, you will get multiple test runs in Qase, one for each browser.

However, there could be an option to report tests to a single run, not as retests, but as parameterized variants of a single case. The qase-playwright reporter doesn't support this option currently, but we can implement it.

**Comment by saysetel** [comment]
Got it, thank you very much for the information!
