### ISSUE TITLE
[qase-cucumberjs] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/src/messages' is not defined

### ISSUE THREAD

**Issue by felipocorrea90** [qase-tms/qase-javascript#533]
Running `cucumber-js -f cucumberjs-qase-reporter --format-options='{\"qaseConfig\": \"./.qaserc\"}' features -r support -r step_definitions` is not working. Showing error `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/src/messages' is not defined by "exports" in .../automation-testing-selenium/node_modules/@cucumber/messages/package.json`.

I tried using both .qaserc and `cucumber-js -f cucumberjs-qase-reporter features -r support -r step_definitions` using ENV values but got the same output.

**Comment by gibiw** [comment]
@felipocorrea90 thanks for noticing! Try to update the qase-cucumberjs reporter to 2.0.0. You can find more details [here](https://github.com/qase-tms/qase-javascript/tree/main/qase-cucumberjs#updating-from-v1)
