### ISSUE TITLE
Playwright: add custom text comments on the test results page

### ISSUE THREAD

**Issue by NickVolynkin** [qase-tms/qase-javascript#590]
Besides attaching custom text snippets as attachments with `qase.attach()` users can find it useful to attach some comments that will be shown right on the results page.

# Value

Such syntax can give users a flexible option to add some textual comments which will be seen right on the test results page, without the need to open attachments.

# Syntax

```javascript
  test('Comment example', async ({ page }) => {
    qase.id(42)
    await page.goto('https://qase.io/');
    
    qase.comment(`Page title: ${page.title()}`)
    expect(await page.title()).toBe('Qase | Test management software for quality assurance');
  });
```

# Implementation

In both API version there are fields responsible for this type of on-page comments.

* https://developers.qase.io/reference/create-result-bulk → `comment`
* https://developers.qase.io/v2.0/reference/create-result-v2 → `message`

Reported with API v1:

<img width="385" alt="Screenshot 2024-05-22 at 15 43 26" src="https://github.com/qase-tms/qase-javascript/assets/8015154/5c909e20-0ad5-4452-9801-4e1c68ee70f3">

Reported with API v2:

<img width="351" alt="Screenshot 2024-05-22 at 15 45 37" src="https://github.com/qase-tms/qase-javascript/assets/8015154/7770b996-01a3-4a9c-a925-28729bd47e7b">

**Comment by cenfun** [comment]
If using `qaseio` API, it can be easily implemented. 
add qase metadata with comments:
```js
/**
 * @qase 1
 * @qase_comment Test case comment here
 */
test('passed test', () => {

});
```
see [example](https://github.com/cenfun/monocart-reporter-examples/tree/main/integrations/qase)

**Comment by gibiw** [comment]
Added to qase-playwright 2.0.4
