### ISSUE TITLE
[qase-cypress-v2] Cannot create run error

### ISSUE THREAD

**Issue by l-oliveira-synd-io** [qase-tms/qase-javascript#616]
No matter what config I change, I'm always getting the `Cannot create run` error. See screenshot
![image](https://github.com/qase-tms/qase-javascript/assets/167244352/3671cc37-b282-4254-a5f3-a12fd556fc51)

Here's my `cypress.config.ts` file.

```
reporter: 'cypress-multi-reporters',
  reporterOptions: {
    reporterEnabled: 'cypress-qase-reporter',
    cypressMochawesomeReporterReporterOptions: {
      charts: true,
    },
    cypressQaseReporterReporterOptions: {
      testops: {
        api: {
          token: '<api_token>',
          host: 'qase.io',
        },
        defect: true,
        run: {
          title: 'Regression test',
          description: 'Regression test run',
          complete: false,
        },
        project: '<project_code>',
        uploadAttachments: true,
        framework: {
          cypress: {
            screenshotsFolder: 'cypress/output/screenshots',
          },
        },
      },
      environment: '<my_env>'
      mode: 'testops',
      captureLogs: true,
    },
```

Am I doing anything wrong?

**Comment by NickVolynkin** [comment]
Code 403 points at a problem with permissions. You can start with checking your API token or creating a new one. Your can also check it on https://developers.qase.io/reference/create-run

**Comment by l-oliveira-synd-io** [comment]
> Code 403 points at a problem with permissions. You can start with checking your API token or creating a new one. Your can also check it on https://developers.qase.io/reference/create-run

Thanks! I actually reached my runs limit! Let's close this one 🙌

**Comment by l-oliveira-synd-io** [comment]
hey @NickVolynkin could you help me setting my api token as an env variable either from `.env` or `cypress.env.json`? I'm facing difficultie on doing it
