### ISSUE TITLE
Not seeing the old syntax supported on v2.0.4

### ISSUE THREAD

**Issue by escosio** [qase-tms/qase-javascript#628]
I recently updated to v2.0.4 and it says that the old syntax is supported but when i run my tests I get this error 
```
qase: qase(caseId) is deprecated. Use qase.id() and qase.title() inside the test body
The following tests are using the old annotation:
```

I'm trying to use this syntax
```
test(qase(2, 'This syntax is still supported'), () => {
    expect(true).toBe(true);
  });
```
I updated imports to be `import { qase } from 'playwright-qase-reporter'`. Am i missing anything?

**Comment by NickVolynkin** [comment]
It's not an error, more of a deprecation message. Old syntax should still work, and test results should be reported.

We wanted to have some way to tell users that they're using a deprecated syntax and, thus, missing all the new features. This message is the best thing we could come up with. We should probably make it clear that the old syntax is still working. And if you can think of a better way communicate this, please tell me.

**Comment by escosio** [comment]
Ah that makes sense, thank you! After further debugging, the issue was actually that I did not update my config correctly and so it was unable to report to Qase. 

Small suggestion that might help others, you may want to update the README to include the `mode: "testops"` portion in the example since that was not clear to me. I had to go through previous release notes to find it 😄

**Comment by NickVolynkin** [comment]
@escosio I've tried to make it sound clear: https://github.com/qase-tms/qase-javascript/pull/629
