### ISSUE TITLE
More than one qase id on one endpoint, its possible?

### ISSUE THREAD

**Issue by arirarira** [qase-tms/qase-javascript#635]
Example : 
// qase: 18230
pm.test(`Validasi Total QTY IN Calculated = ${totalInCalculated} dengan QTY IN per kendaraan = ${qtyIn}.`, function () {
    pm.expect(totalInCalculated).to.eql(qtyOut);
});

// qase: 18231
pm.test(`Validasi Total QTY OUT Calculated = ${totalOutCalculated} dengan QTY OUT per Kendaraan = ${qtyOut}.`, function () {
    pm.expect(totalOutCalculated).to.eql(qtyOut);
});

**Comment by NickVolynkin** [comment]
@arirarira it should be possible. What test framework do you use?

**Comment by arirarira** [comment]
> @arirarira it should be possible. What test framework do you use?

i'm using newman-qase-reporter

**Comment by NickVolynkin** [comment]
With Newman, you can list case IDs in the comment
```javascript
// qase: 18230 18231
pm.test(Validasi Total QTY IN Calculated = ${totalInCalculated} dengan QTY IN per kendaraan = ${qtyIn}., function () {
pm.expect(totalInCalculated).to.eql(qtyOut);
});
```
