### ISSUE TITLE
Question: Updating steps

### ISSUE THREAD

**Issue by anastasiia-bunch** [qase-tms/qase-javascript#643]
Good day!
Thank you for qase-reporter, love to use it. 

I notice that after the run of playwright e2e tests test cases steps in Qase itself become updated. 
While checking documentation I haven't found any information about steps. 
Could you tell me please how can I disable it (because I also need data and expected result in test cases).
<img width="690" alt="image" src="https://github.com/user-attachments/assets/1dc85075-4579-4307-bd90-ecf1cd87e6cb">

Thanks!

**Comment by NickVolynkin** [comment]
Hey, thanks for the nice words!

Did it happen to all your tests or only the parametrized ones? Were you using your personal API token or a test reporter's token?

**Comment by anastasiia-bunch** [comment]
I was checking if is there a flag as `updateTestCases: false` for config, but can't find any.

**Comment by gibiw** [comment]
Now you can flexibly configure which fields to update in the project settings.

<img width="570" alt="image" src="https://github.com/user-attachments/assets/1483e93c-d786-4585-987e-d165b166b8c0">

**Comment by RichWattieCera** [comment]
I'd also like to add know the answer to this part of the original question...
I'm using playwright-qase-reporter. Is it currently possible to set data or the expected result for steps?

> (because I also need data and expected result in test cases)

**Comment by anastasiia-bunch** [comment]
@gibiw Thank you!
