### ISSUE TITLE
Question: Is it possible to fail Test case wh 1 of steps is failed?

### ISSUE THREAD

**Issue by mi4i0** [qase-tms/qase-javascript#651]
Our test cases have structure looks like this:
![image](https://github.com/user-attachments/assets/cbc77f55-2939-4ac0-bd64-868cf0f467c6)

Where next test steps are separate tests in automation but have the same qase.id():
1. Check of ACHIEVEMENT NAME field
2. Check of ISSUER field
3. Check of ACHIEVEMENT DATE

When I run this tests via automation TC 1 and 2 passed, TC 3 failed. In total TC in QASE would be marked as passed. 
![image](https://github.com/user-attachments/assets/fc79caf9-277c-43bc-95fc-e1f7d83d5f9d)

**Question:** Can TC be marked as failed in QASE if 1 of those TC reported as failed?

**Comment by gibiw** [comment]
This happens because you have specified the same Qase ID for different tests.

There are two possible solutions:
1. Split the manual test case into 3 separate ones and assign a unique Qase ID to each automated test.
2. Combine the 3 automated tests into one using steps or any other method.
