### ISSUE TITLE
qase-playwright: Unable to upload test results. Error on uploading results: Bad request. 

### ISSUE THREAD

**Issue by anastasiia-bunch** [qase-tms/qase-javascript#676]
Good day, 

I use playwright Qase reporter for sending test results into Qase. 
Here are the current versions:
```
"@playwright/test": "^1.41.1"
"playwright-qase-reporter": "^2.0.5"
```

After I disabled adding new test cases (updating test cases was disabled from the start):
<img width="806" alt="image" src="https://github.com/user-attachments/assets/c27b691b-d9d1-452f-81f7-1c344f7564a6">
<img width="857" alt="image" src="https://github.com/user-attachments/assets/d2a3a24e-24c9-4e99-a797-5d9b2be995f2">

 I started to get errors:
```
Error:  qase: Unable to publish the run results to the upstream reporter:
Error: Error on uploading results: Bad request. 
```

Could you tell me why I was getting this error? 
I saw [this thread](https://github.com/qase-tms/qase-javascript/issues/648) but here there is a recommendation to enable the ability to add new test cases, which is not an option in my case (I don't need to add new cases or update existing one).

Thank you!

**Comment by gibiw** [comment]
@anastasiia-bunch Hello! 

You are getting this error because you are trying to upload test results that are not yet in the Qase repository.
You need to add QaseID for each of your tests and then the results will be successfully uploaded.

For example, 
``` typescript
import { qase } from 'playwright-qase-reporter';

  test(qase(2, 'simple test'), async () => {
     // do something...
  });
```

We also recommend updating to the latest version of the reporter 2.0.12.

**Comment by anastasiia-bunch** [comment]
Got it, thank you very much!

**Comment by anastasiia-bunch** [comment]
UPD: there are no test cases without qase id, but one test case is set as **skip**
After removing the skip function qase-playwright reports work again.
