### ISSUE TITLE
[qase-javascript] custom reporter 

### ISSUE THREAD

**Issue by Qvatra** [qase-tms/qase-javascript#698]
Hello,
I'm trying to create simple plugin for Vitest tests to send to qase test result so that it will be visible in corresponding (by id) testcase run history.

so far I have this but it doesnt add results in testcase run history:
```import { QaseReporter, ConfigLoader } from 'qase-javascript-commons';

// Use loadConfig to load environment and other settings
const config = (new ConfigLoader({}, ['src/plugins/qase.config.json'])).load();

// Extract API token and project from loaded config
const qaseApiToken = config.testops?.api.token;
const projectCode = config.testops?.project;

// Initialize QaseReporter using the config
const reporterOptions = {
	...config,
	apiToken: qaseApiToken,
	projectCode,
};

const reporter = new QaseReporter(reporterOptions);

const result = {
	case_id: 9,
	title: 'Sample Test',
	execution: {
		status: 'passed'
	},
	status: 'passed',
};
await reporter.addTestResult(result);
```

and config is the following:
```{
	"mode": "testops",
	"fallback": "report",
	"debug": true,
	"environment": "local",
	"captureLogs": false,
	"report": {
		"driver": "local",
		"connection": {
			"local": {
				"path": "./build/qase-report",
				"format": "json"
			}
		}
	},
	"testops": {
		"api": {
			"token": "123",
			"host": "qase.io"
		},
		"run": {
			"title": "Regress run",
			"description": "Regress run description",
			"complete": true
		},
		"defect": false,
		"project": "INSPIRE",
		"batch": {
			"size": 100
		}
	}
}
```

Is there a guide/docs on how I can achieve this with qase-javascript lib?
can you please guide me a bit?

**Comment by gibiw** [comment]
Hi! 

You can see an example of any of our reporters. For example, Playwright: https://github.com/qase-tms/qase-javascript/blob/main/qase-playwright/src/reporter.ts

When using QaseReporter you need to call the following methods in the given order: 
- startTestRun - creates a new test run in the Qase
- addTestResult - adds a test results to a local storage
- publish - sends test results and completes the test run

**Comment by Qvatra** [comment]
@gibiw thank you for your reply. 

Eventually i decided to just use QaseApi functions for reporting:

```
import { ConfigLoader } from 'qase-javascript-commons';
import { QaseApi } from 'qaseio';

// Use loadConfig to load environment and other settings
const config = (new ConfigLoader({}, ['src/plugins/qase.config.json'])).load();

// Extract API token and project from loaded config
const qaseApiToken = config.testops?.api.token;
const projectCode = config.testops?.project;

console.log('API Token:', qaseApiToken);
console.log('Project Code:', projectCode);

const qaseApi = new QaseApi({
	token: qaseApiToken
});

qaseApi.runs.createRun(projectCode, { title: 'test123', cases: [9]});
```

but for some reason it doesnt create run... also print no errors or warnings. debug is on.
i tried the same call here https://developers.qase.io/reference/create-run and it works fine.
What do i do wrong?

**Comment by gibiw** [comment]
Example how to initialise APi client: 
https://github.com/qase-tms/qase-javascript/blob/main/qase-javascript-commons/src/qase.ts#L519

Example how to create Test run
https://github.com/qase-tms/qase-javascript/blob/main/qase-javascript-commons/src/reporters/testops-reporter.ts#L648

**Comment by Qvatra** [comment]
@gibiw 
hmm i just noticed that documentation in https://github.com/qase-tms/qase-javascript/tree/main/qaseio is written not for the latest version that is installed with `npm install qaseio`

i can see that because in installed versione there is no such function as `qase.projects.getAll()` but in lower versions it exists...

**Comment by Qvatra** [comment]
@gibiw , thank you!
now i get this error:
```
Error: Cross origin http://localhost:3000 forbidden
    at dispatchError (/Users/oleksandrzinchenko/projects/phoenix/frontend/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:63:19)
    at validCORSHeaders (/Users/oleksandrzinchenko/projects/phoenix/frontend/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:75:5)
    at validCORSPreflightHeaders (/Users/oleksandrzinchenko/projects/phoenix/frontend/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:89:8)
```
on axios api calls that is used in qaseio..

chat gpt suggesting to run it in node env instead of jsdom but my vitests are using jsdom.
Not sure how I can proceed.. any idea?

**Comment by gibiw** [comment]
@Qvatra Are you sure you are configuring the client correctly and loading the config?

**Comment by Qvatra** [comment]
@gibiw well the way im doing it is shown in my first post to this issue.
and console.log indeed shows that file is read correctly and project code and token are the same that i use in https://developers.qase.io/reference/create-run

**Comment by gibiw** [comment]
@Qvatra It works for me:
```js
const { QaseApi } = require('qaseio');

const options = {
    token: 'token',
    host: 'https://api.qase.io',
}

const apiClient = new QaseApi(options);


apiClient.runs.createRun('project_code', {title:"test"}).then((response) => {
    console.log(response);
}).catch((error) => {
    console.error(error);
});
```

**Comment by Qvatra** [comment]
I had some corse issues that were not logged out. thanks for the help!
