### ISSUE TITLE
[qase-wdio] Error: "Some reporters are still unsynced: WDIOQaseReporter" 

### ISSUE THREAD

**Issue by dbenages-at-wiris** [qase-tms/qase-javascript#711]
When running regressions with a lot of tests (specially when a lot of them fail and screenshot upload is active) not all results are uploaded to Qase Test Run.

Timeline view in the Test Run shows large gap where nothing is being updated 
![imagen](https://github.com/user-attachments/assets/d96a1d63-384f-4eba-a37d-0873329ac513)

Reviewing logs this gaps match the following error message 
``` 
ERROR @wdio/runner: Error: Some reporters are still unsynced: WDIOQaseReporter
```
Increasing batch size helps, but does not fix the issue entirely.

Version: 1.0.0-beta.4

**Comment by gibiw** [comment]
@dbenages-at-wiris Hi! Yes, this can happen if the reporter does not have time to upload all the data in a certain time. You can control the interval with the `reporterSyncTimeout` parameter in `wdio.conf.js`. Try increasing it

**Comment by dbenages-at-wiris** [comment]
@gibiw Oh got it. I looked for some parameter like that but didn't find it in the documentation. I guess I missed it. 

I will try that! thanks :)
