### ISSUE TITLE
[Question][playwright] cannot update test result to qase test run automatic (need to manually create test run id)

### ISSUE THREAD

**Issue by Thanasornsawan** [qase-tms/qase-javascript#729]
Hi I try everything same like example config. with the script below. 

```
const { test, expect } = require('@playwright/test');
import { qase } from 'playwright-qase-reporter';

// A simple function for addition
function add(a, b) {
  return a + b;
}

// A simple function for subtraction
function subtract(a, b) {
  return a - b;
}

test.describe('Simple Calculation Tests', () => {

  test('calculation additional logic should pass', async () => {
    qase.id(1);
    qase.title('Calculation additional logic should pass');
    qase.fields({ 'severity': 'normal', 'priority': 'low' });
    await test.step("Step 1: 2+3 should be 5", async () => {
      const result = add(2, 3);
      expect(result).toBe(5); // This test will pass
    });
  });

  test('calculation subtraction logic should fail', async () => {
    qase.id(2);
    qase.title('calculation subtraction logic should fail');
    qase.fields({ 'severity': 'normal', 'priority': 'low' });
    await test.step("Step 1: 5-3 should not be 5", async () => {
      const result = subtract(5, 3);
      expect(result).toBe(5); // This test will fail because the result should be 2
    });
  });
});
```

The playwright.config.js file

```
// @ts-check
const { devices } = require('@playwright/test');
require('dotenv').config({ path: '.env' });

const config = {
  testDir: './tests',
  retries: 0,
  timeout: 30 * 1000,
  expect: {
    timeout: 5000,
  },
  reporter: [
    ["list"],  
    //['@zealteam/testrail-reporter'],
    [
      'playwright-qase-reporter',
      {
        debug: true,
        testops: {
          api: {
            token: process.env.QASE_TOKEN,
          },
          project: 'PT',
          uploadAttachments: true,
          run: {
            complete: true,
          },
        },
      },
    ],
  ],
  use: {
    browserName: 'chromium',  
    headless: true,           
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
  },
};

module.exports = config;
```

What's I am missing? I can't push the result to Qase.
<img width="1427" alt="Screenshot 2567-12-30 at 00 19 44" src="https://github.com/user-attachments/assets/86c10eb7-71ce-4a8d-b40c-7dcff7f50edb" />
<img width="1418" alt="Screenshot 2567-12-30 at 00 20 04" src="https://github.com/user-attachments/assets/c83df015-1fff-42e6-b361-4477310d3b8b" />
<img width="1406" alt="Screenshot 2567-12-30 at 00 20 14" src="https://github.com/user-attachments/assets/47062b02-f9bf-44bc-86cb-06b66af5bc58" />
<img width="1340" alt="Screenshot 2567-12-30 at 00 21 00" src="https://github.com/user-attachments/assets/d01acfd2-f52d-4327-874e-5eb80d878369" />
<img width="1397" alt="Screenshot 2567-12-30 at 00 35 10" src="https://github.com/user-attachments/assets/68c88f7d-34d4-4652-971d-1c445ff36b89" />

### I try to understand what's happend. So, I manually create 1 test run and then run script again and result show that script can sent result to Qase but if I not create test run manually. It not create new test run and sent result to qase for me.
<img width="1335" alt="Screenshot 2567-12-30 at 01 14 28" src="https://github.com/user-attachments/assets/5c7b4259-3756-4cdb-9d08-1fa53af8e6c0" />

**Comment by gibiw** [comment]
@Thanasornsawan Hello! Thank you for reaching out. 
Please try running the example I’ve provided below. If it doesn’t work, kindly send the complete logs for further analysis.
[playwright.zip](https://github.com/user-attachments/files/18272194/playwright.zip)

**Comment by Thanasornsawan** [comment]
> @Thanasornsawan Hello! Thank you for reaching out. Please try running the example I’ve provided below. If it doesn’t work, kindly send the complete logs for further analysis. [playwright.zip](https://github.com/user-attachments/files/18272194/playwright.zip)

Thank you. It turn out I read the documentation wrong at line 
`QASE_TESTOPS_RUN_ID - Pass Run ID from ENV and override reporter option testops.run.id`
In the beginning I set `export QASE_TESTOPS_RUN_ID=1`, that is why it looking for id 1 only and have error because it not exist.
Now I `unset QASE_TESTOPS_RUN_ID` and everything works perfect. Thank you for your time try to help.
