### ISSUE TITLE
When a run already exists in Qase, it is not possible to report from cypress

### ISSUE THREAD

**Issue by Itzimusi** [qase-tms/qase-javascript#77]
I have installed the cypress-qase-reporter for my project
but when I run the tests, it only creates the test run for the first cypress spec executed; for the following specs it shows me an error qase: Error on creating run Error: Request failed with status code 403. 

- I have an "old" test run in my project
- and the reporter configured in my cypress.json
"cypressQaseReporterReporterOptions": {
"apiToken": "XXXXXXXXXXXXXXXX",
"projectCode": "MS",
"logging": true
}
- QASE_REPORT=1 npx cypress run --spec cypress/integration/authentication/login.js
- -> qase: Project MS exists
        qase: Error on creating run Error: Request failed with status code 403
- I delete the old run, that was run id 5
- - QASE_REPORT=1 npx cypress run --spec cypress/integration/authentication/login.js
- -> qase: Project MS exists
        qase: Using run 7 to publish test results

So, everytime a run already exists in Qase, it is not possible to report from cypress

***I am using version 1.2.0; newer versions do not work on my system

**Comment by 1ivliev** [comment]
Hi! Is the problem reproducible on the latest version of cypress-qase-reporter?

**Comment by 1ivliev** [comment]
@Itzimusi, hi! Is the problem reproducible on the latest version of cypress-qase-reporter?
