### ISSUE TITLE
qase.runs.getAll by title filter

### ISSUE THREAD

**Issue by sasha-t** [qase-tms/qase-javascript#78]
Hi!
Can I search runs by title or other fields?

Or I can use status filter only?

**Comment by pyatyispyatil** [comment]
@sasha-t Unfortunately our [public api](https://developers.qase.io/reference/get-runs) currently only supports filtering by status, milestone and environment. In [the JS api middleware](https://github.com/qase-tms/qase-javascript/blob/09e0a4baa6870048e24878d537ee07d0425a948c/qaseio/src/models/runs.ts#L10), only the status field is available.

We will soon update the public api and fix this omission.)

**Comment by sasha-t** [comment]
Thank you for your answer)
I solved this problem by filtering response in native js.

I will wait for your update 🙌

**Comment by pyatyispyatil** [comment]
@sasha-t you can track progress on this issue https://github.com/qase-tms/qase-javascript/issues/79
