### ISSUE TITLE
[Cypress] Could not send all results for 30 seconds after run Error

### ISSUE THREAD

**Issue by sasha-t** [qase-tms/qase-javascript#81]
Sometimes I get reporter error:
`qase: Could not send all results for 30 seconds after run. Please contact Qase Team.`
sometimes not...

and I don't understand why, because I see all the results of sent cases in TestRun.

Can you help me with this case? What am I doing wrong?

Thank you.

**Comment by 1ivliev** [comment]
@sasha-t, hi! We are dealing with your problem, please tell us your system configuration and how often an error message occurs (but data is being pooled)?

**Comment by rezmuh** [comment]
Hi @1ivliev I am also experiencing this issue where we run it from an M1 machine (if that makes a difference). What information do you need so we can help?

**Comment by 1ivliev** [comment]
At the moment we are aware of the problem, we have a task to improve the reporter in the backlog. In the next sprint, we will update the JS client, and then we will work directly with `Cypress`. I will notify you when it is published in NPM.

**Comment by sorinciobanescu** [comment]
I have the same problem, I'm waiting for the fix :). Thanks

**Comment by 1ivliev** [comment]
We have released an update `cypress-qase-reporter` to the version `v1.4.2-alpha.2` fixing this problem. You can use the new version from [source](https://github.com/qase-tms/qase-javascript/tree/master/qase-cypress) or wait for publication on NPM.

**Comment by 1ivliev** [comment]
Good afternoon. We are closing this appeal because we have not received a response. In case the problem occurs again, please contact us. Have a nice day.

**Comment by sorinciobanescu** [comment]
I tested the cypress-qase-reporter version 1.4.2-alpha.2, and I received the following error: "Publication is started
(node:8560) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Error till publishing Error: Request failed with status code 403
    at createError 
..." the report is not published. With the previous npm package (ver. 1.4.1), I received that error but my report was published. I rollback to previous package, this fix doesn't help me.
