### ISSUE TITLE
Unable to use the playwright reporter

### ISSUE THREAD

**Issue by alkanna** [qase-tms/qase-javascript#90]
Hello,

The playwright reporter does not seem to be published to npm.
Also, I am getting an error if I install the module directly from git :
```
Error: Cannot find module 'node_modules/playwright-qase-reporter/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by alkanna** [comment]
Pinging @alexneo2003 since you implemented this. Does this commit need to be tagged ?

**Comment by alexneo2003** [comment]
@kamilsk 
can you answer - why qase-playwright not been published at npm?

> Pinging @alexneo2003 since you implemented this. Does this commit need to be tagged ?
@alkanna 
i'm think you will can't correctly install package directly from github because it not have 'dist' folder with compiled files

**Comment by alkanna** [comment]
I get that, I managed to make it work locally by manually building it, but the proper fix would be to publish it to npm yes.

**Comment by alkanna** [comment]
I think the following needs to be done :
- Tag a release after your PR was merged
- Update the npm github workflow so that this new tag gets published

**Comment by kamilsk** [comment]
Hi, folks!

> can you answer - why qase-playwright not been published at npm?

Yes, I could. We have a plan to publish it this week.

**Comment by kamilsk** [comment]
published https://www.npmjs.com/package/playwright-qase-reporter

fill free to reopen it, if something get wrong
